### ISSUE TITLE
Example seems incorrect

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/orm-updating-records#20]
```class Song
  ...
 
  def update
    sql = "UPDATE songs SET name = ?, album = ? WHERE name = ?"
    DB[:conn].execute(sql, self.name, self.album, self.name)
  end
end
```

in this example, wouldn't this method NEVER update anything? Isn't this just equivalent to "UPDATE songs SET name = 'Hella', album = ? WHERE name = 'Hella'", which is different than
"UPDATE songs SET name = 'Hello', album = ? WHERE name = 'Hella'"?

the example doesn't seem to do anything.

**Comment by maxwellbenton** [comment]
Hi @Samoth112, thank you for providing feedback.

You are correct, this example doesn't do anything, as per the readme: "The above #update method will not work if we are trying to update the name of a song."

Later on in the lesson, the correct update method uses `id` as instead of `name`: https://github.com/learn-co-curriculum/orm-updating-records#using-id-to-update-records

I'm going to close this for now, but if you feel this issue is not resolved, please feel free to reopen.
